name: CI

on:
  push:
    branches:
      - main

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            lfs: 'true'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Lint source code
        run: make lint

  testing:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            lfs: 'true'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

      # - name: Build docs
      #   run: make docs

      - name: Upload backend coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
